// tools/tts.mjs tarafından üretilir, elle düzenlemeyin.
export const TTS = {
  "voice": "tr-TR-Chirp3-HD-Leda",
  "files": {
    "82d1e6ae": "Doğru!",
    "485abfb5": "Harika!",
    "d965f2b9": "Hmm, tam değil. Bir daha dene!",
    "0eabbf2b": "Bravo! Resmi tamamladın.",
    "48ecc799": "Merhaba! Ben Nota. Bugün birlikte keman çalmayı öğreneceğiz.",
    "97ef46f6": "Keman, telli ve yaylı bir çalgıdır. Sesi, insan sesine en çok benzeyen çalgılardan biri olarak bilinir.",
    "ca4cc9dc": "Kemanın parçalarını tanıyalım: kıvrım ve burgular, klavye, gövde, eşik, f delikleri, kuyruk ve çenelik.",
    "ff855989": "Dört tel eşiğin üzerinden geçer. Yay teli titreştirir, eşik bu titreşimi gövdeye taşır, gövde de sesi büyütür.",
    "23a1fc52": "Teller gövdenin üzerinde hangi parçanın üstünden geçer?",
    "bccc657a": "Bu da yay. Ucu, çubuğu, kılları ve topuğu var. Kıllara reçine sürmezsek yay teli kavrayamaz ve ses çıkmaz.",
    "1dd031fc": "Yayın kıllarına ne sürülür?",
    "70d218db": "Harika! Kemanı ve yayı tanıdın. Sırada kemanı doğru tutmak var.",
    "2906af4d": "Keman sol omzumuza yerleşir. Çenemizi çeneliğe hafifçe koyarız; kemanı sıkmadan, başımızın ağırlığıyla tutarız.",
    "0e9c942e": "Sol el sapı nazikçe tutar; bilek düz kalır, avuç sapa yapışmaz. Omuzlar rahat, sırt dik.",
    "1452a988": "Keman hangi omza yerleşir?",
    "359574d5": "Süper! Kemanı doğru tutmayı öğrendin. Sırada yay tutuşu var.",
    "2baec10a": "Yayı tutarken başparmak bükük durur ve ucuyla topuğun hemen önüne dokunur. Diğer parmaklar çubuğun üstünden yumuşakça sarkar.",
    "064d37fe": "Serçe parmak yuvarlak durur ve ucuyla çubuğun üstüne konar. Elin gevşek olsun, yayı sıkma.",
    "b208b0e0": "Yay tutuşunda başparmak nasıl durur?",
    "6c8d97e6": "Yayı eşik ile klavyenin arasından, tellere dik çekeriz. Yay eğik giderse ses cızırtılı olur.",
    "92ca2405": "Yay tellere nasıl çekilmeli?",
    "2ef69d49": "Bravo! Artık yayı tutmayı biliyorsun. Bir sonraki derste ilk seslerimizi çıkaracağız.",
    "d256e825": "Kemanın dört teli var: kalından inceye Sol, Re, La ve Mi. Hiçbir parmak basmadan çalınan tele boş tel deriz.",
    "7a1eab85": "İlk olarak La telini boş çalalım. Yayı La teline koy ve topuktan uca kadar düz çek.",
    "339d6d2e": "Şimdi sen çal: La.",
    "ab4ff0ec": "Şimdi Re teli. Sağ dirseğini biraz kaldır ki yay yalnızca Re teline değsin.",
    "8eb25cf4": "Şimdi sen çal: Re.",
    "b27d439a": "Mi teli en ince teldir; sesi parlak çıkar. Dirseğini biraz indir ve yayı hafifçe çek.",
    "28796f00": "Şimdi sen çal: ince Mi.",
    "94e52d49": "Son olarak en kalın tel, Sol teli. Dirseğini en yükseğe kaldır ve yayı sakin çek.",
    "1a2e4832": "Şimdi sen çal: kalın Sol.",
    "b2ec88e5": "Muhteşem! Dört boş teli de çaldın. Şimdi Boş Tel Treni şarkısıyla ilk resmini çiz!",
    "dfa55474": "Şimdi parmak basma zamanı. La telinde birinci parmağını ilk bandın üzerine koy: bu nota Si.",
    "a1fea02f": "Şimdi sen çal: Si.",
    "c804a13d": "İkinci parmağını, üçüncü parmağın yerine yakın koy; buna yüksek 2 deriz. Bu nota Do diyez.",
    "ee88a582": "Şimdi sen çal: ince Do diyez.",
    "2c4b5238": "Üçüncü parmağını ikinci parmağının hemen yanına yapıştır. İşte ince Re!",
    "7ff835b9": "Şimdi sen çal: ince Re.",
    "01ba5ef8": "La, Si, Do diyez ve Re: dört nota bir merdiven gibi yükseliyor.",
    "c366dcac": "Do diyez için ikinci parmak nerede durur?",
    "c753682f": "Önce Salıncak ve Merdiven ile ısın; sonra Sıcak Çörekler, Tembel Çocuk ve Küçük Kuzu seni bekliyor!",
    "2af9b2d9": "Re telinde birinci parmak Mi notasını verir. Parmağını ilk bandın üzerine koy.",
    "48a83395": "Şimdi sen çal: Mi.",
    "14d7de2c": "İkinci parmak yine yüksek: üçüncü parmağın yerine yakın. Bu nota Fa diyez.",
    "0263b49f": "Şimdi sen çal: Fa diyez.",
    "436a5e86": "Üçüncü parmağını ikinci parmağının yanına yapıştır: işte Sol!",
    "3190c267": "Şimdi sen çal: Sol.",
    "de0aa7d8": "Re, Mi, Fa diyez, Sol ve boş La: Re majör dizinin ilk beş notası!",
    "bb094cd8": "Re telinde üçüncü parmak hangi notayı verir?",
    "9c12d134": "Harika! Artık Neşeye Övgü şarkısını çalıp bir keman resmi ortaya çıkarabilirsin.",
    "f930e14a": "Müzikte her notanın bir süresi vardır. Bu süreyi eşit vuruşlarla sayarız: bir, iki, üç, dört.",
    "9e789629": "Birlik dört vuruş, ikilik iki vuruş, dörtlük bir vuruş, sekizlik ise yarım vuruş sürer. Uzun notada yayı yavaş, kısa notada hızlı çekeriz.",
    "ce2291f9": "Kemanda yayın yönü de yazılır. Kapı gibi olan işaret aşağı yay demek: yayı topuktan uca doğru çekeriz. V işareti ise yukarı yay: uçtan topuğa doğru iteriz.",
    "700052c7": "V işareti ne demek?",
    "63c3132f": "Bir soru daha!",
    "59fc1635": "Bir ikilik nota kaç dörtlük eder?",
    "62e29bf6": "Süper! Şarkılarda hem nota sürelerine hem de yay yönlerine dikkat et.",
    "a8255e3f": "Mi telinde birinci parmak ince Fa diyez notasını verir.",
    "73c859aa": "Şimdi sen çal: ince Fa diyez.",
    "52d198fc": "İkinci parmak yine yüksek: üçüncü parmağın yerine yakın. Bu nota ince Sol diyez.",
    "fa0c3993": "Şimdi sen çal: ince Sol diyez.",
    "144b92e9": "Üçüncü parmağını ikinci parmağının yanına koy: ince La. Boş La telinden tam bir oktav yukarıda!",
    "5d8467c7": "Şimdi sen çal: ince La.",
    "13eb299c": "Muhteşem! Artık Daha Dün Annemizin şarkısını çalıp gökyüzüne bir yıldız çizebilirsin."
  }
};
