// tools/tts.mjs tarafından üretilir, elle düzenlemeyin.
export const TTS = {
  "voice": "tr-TR-Chirp3-HD-Leda",
  "files": {
    "42923990": "Şimdi sihirli kısım: Pes Mi’nin parmaklarını bozmadan havayı daha hızlı ve dar üflersen, bir oktav yukarıdaki ince Mi çıkar!",
    "82d1e6ae": "Doğru!",
    "485abfb5": "Harika!",
    "d965f2b9": "Hmm, tam değil. Bir daha dene!",
    "0eabbf2b": "Bravo! Resmi tamamladın.",
    "71592b97": "Merhaba! Ben Nota. Bugün birlikte yan flüt çalmayı öğreneceğiz.",
    "b00329e7": "Yan flüt, insanlığın en eski çalgılarından birinin modern hâli. Sesi bir kuş ötüşü kadar parlak!",
    "19f97f94": "Flüt üç parçadan oluşur: baş, gövde ve ayak.",
    "7cc7e440": "Baş kısmında dudaklığı ve üfleme deliğini görüyorsun. Sesi tam burada üretiyoruz.",
    "360a69bf": "Gövdede parmaklarımızı koyduğumuz anahtarlar var. Anahtarlara basınca flütün içindeki hava sütunu uzar ya da kısalır; böylece farklı notalar çıkar.",
    "747310b9": "Sesi flütün hangi kısmında üretiyoruz?",
    "98ecff7e": "Flütü yere paralel ve sağ tarafına doğru tutarız. Karşıdan bakınca flüt sola uzanıyor gibi görünür. Adı da buradan gelir: yan flüt!",
    "e79d71e6": "Yan flüt hangi yöne doğru tutulur?",
    "0a108ae9": "Harika! İlk dersi bitirdin. Sırada ilk sesimizi çıkarmak var.",
    "3e45ec2c": "Boş bir şişenin ağzına yandan üflediğinde \"huuu\" diye bir ses çıktığını hiç fark ettin mi?",
    "c5a978ff": "İşte flüt de tam olarak böyle çalışır. Havayı deliğin içine değil, karşı kenarına üflüyoruz.",
    "9335329e": "Dudaklarını hafifçe gerip \"pu\" der gibi küçük bir açıklık bırak. Yanakların şişmesin.",
    "920c96db": "Hava akımı deliğin karşı kenarına çarpar ve ikiye ayrılır: yarısı flütün içine, yarısı dışarıya gider. Ses bu titreşimden doğar.",
    "712ed4b3": "Havayı nereye üflemeliyiz?",
    "bf28bced": "Şimdi sıra sende! Önce sadece baş kısmını al, dudaklığı alt dudağının hemen altına yasla ve uzun, sakin bir ses çıkarmayı dene.",
    "b0ff14e6": "Şimdi sen dene: uzun ve sakin bir ses çıkar.",
    "43d94c03": "Bravo! İlk sesini çıkardın. Ses çıkmazsa dert etme; dudak açıklığını ve flütün açısını azar azar değiştirerek dene.",
    "851cbac4": "Flüt çalarken nefesimizi göğsümüze değil, karnımıza alırız. Karnını bir balon gibi düşün.",
    "e06e6ae5": "Nefes alırken omuzların kalkmasın. Karnın şişsin, sonra havayı yavaş yavaş ve kontrollü bırak.",
    "4e9bbbe2": "Nefes egzersizi: 4 say nefes al, 8 say üfle.",
    "816a647e": "Duruşa gelelim: Dik dur ya da otur, omuzların rahat olsun. Dirseklerini gövdene yapıştırma; flütü kolların taşısın, başını hafifçe sola çevir.",
    "1d1e98e7": "Doğru nefes nasıl alınır?",
    "44c9be0c": "Süper! Nefesin ve duruşun hazır. Bir sonraki derste ilk notamızı öğreniyoruz.",
    "5480ec5c": "İlk notamız Si! Sol başparmağını alttaki başparmak anahtarına, sol işaret parmağını ilk anahtara koy.",
    "a1c65bba": "Sağ serçe parmağın Mi bemol anahtarına bassın. Bu anahtar flütü dengede tutar ve neredeyse bütün notalarda basılı kalır.",
    "565d81b6": "Porte üzerinde Si, ortadaki üçüncü çizginin üzerinde durur. Nasıl duyulduğunu dinle.",
    "e45b6071": "Şimdi sen çal! Si notasını uzun ve sakin bir şekilde tut.",
    "a1fea02f": "Şimdi sen çal: Si.",
    "fd80571b": "Tebrikler, ilk notanı çaldın! Şimdi Si Treni şarkısıyla ilk resmini çiz, sonra La ve Sol notalarına geçelim.",
    "221ca7e1": "Si'nin parmaklarına sol orta parmağını eklersen La çıkar.",
    "339d6d2e": "Şimdi sen çal: La.",
    "b9c2298a": "Bir parmak daha: sol yüzük parmağını da kapat. İşte Sol!",
    "3190c267": "Şimdi sen çal: Sol.",
    "ee269f74": "Üç notayı sırayla dinle: Si, La, Sol. Parmakların bir merdivenden iniyor gibi.",
    "4bfb9806": "Sol notası için sol elinde kaç parmak kapalı? (başparmak hariç)",
    "c64221dd": "Artık üç nota biliyorsun! Önce Salıncak ve Merdiven ile ısın, sonra Sıcak Çörekler’i çal.",
    "0b2b679a": "Daha ince notalara çıkalım. İnce Do için yalnızca sol işaret parmağın ve sağ serçe parmağın basılı. Başparmağını kaldır!",
    "c4b4a241": "Şimdi sen çal: ince Do.",
    "dbfa9f39": "İnce Re biraz farklı: sol işaret parmağını kaldır, diğer parmakların hepsini kapat. Sağ serçe parmak bu sefer havada.",
    "7ff835b9": "Şimdi sen çal: ince Re.",
    "7e4f022d": "Artık beş nota biliyorsun: Sol, La, Si, Do ve Re! Porte üzerinde bir merdiven gibi yükseliyorlar.",
    "1679cdce": "İnce Re çalarken hangi parmak havada kalır?",
    "00b04d5b": "Harika! Önce kısa Tembel Çocuk şarkısını dene, sonra Küçük Kuzu ve Neşeye Övgü’yü çalabilirsin.",
    "f930e14a": "Müzikte her notanın bir süresi vardır. Bu süreyi eşit vuruşlarla sayarız: bir, iki, üç, dört.",
    "c66f2f95": "Birlik nota içi boş bir yuvarlaktır ve dört vuruş sürer. İkilik notanın bir sapı vardır ve iki vuruş sürer.",
    "9b0f3583": "Dörtlük nota içi dolu ve sapılıdır, bir vuruş sürer. Sekizliğin bir de bayrağı vardır, yarım vuruş sürer.",
    "727c7c4e": "Hangisi en uzun süren notadır?",
    "63c3132f": "Bir soru daha!",
    "59fc1635": "Bir ikilik nota kaç dörtlük eder?",
    "af646fe5": "Süper! Şarkılarda notaların sürelerine dikkat ederek çalmayı unutma.",
    "d1bdfdb8": "Pes Re için bütün delikleri kapat, sağ serçe parmak havada kalsın. Pes notalarda havayı yavaş ve geniş üfle.",
    "85290f78": "Şimdi sen çal: pes Re.",
    "1877f0ab": "Mi için sağ yüzük parmağını kaldır ve sağ serçe parmağını tekrar Mi bemol anahtarına koy.",
    "aaf660a9": "Şimdi sen çal: pes Mi.",
    "28796f00": "Şimdi sen çal: ince Mi.",
    "13eb299c": "Muhteşem! Artık Daha Dün Annemizin şarkısını çalıp gökyüzüne bir yıldız çizebilirsin."
  }
};
